In [35]:
import pandas as pd
import numpy as np

In [36]:
movies = pd.read_csv(r"C:\Users\91988\Downloads\tmdb_5000_movies.csv\tmdb_5000_movies.csv")
credits = pd.read_csv(r"C:\Users\91988\Downloads\tmdb_5000_credits.csv\tmdb_5000_credits.csv")

In [37]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [38]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [39]:
credits.drop(columns=["movie_id"],inplace=True)

In [40]:
credits.isnull().sum()

title    0
cast     0
crew     0
dtype: int64

In [41]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [42]:
movies.shape

(4803, 20)

In [43]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [44]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [45]:
movies.drop(columns=["homepage","tagline","budget","id","revenue"],inplace=True)

In [46]:
movies.isnull().sum()

genres                  0
keywords                0
original_language       0
original_title          0
overview                3
popularity              0
production_companies    0
production_countries    0
release_date            1
runtime                 2
spoken_languages        0
status                  0
title                   0
vote_average            0
vote_count              0
dtype: int64

In [47]:
movies.dropna(inplace=True)

In [48]:
movies.isnull().sum()

genres                  0
keywords                0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
release_date            0
runtime                 0
spoken_languages        0
status                  0
title                   0
vote_average            0
vote_count              0
dtype: int64

In [49]:
movies = movies.merge(credits,on="title")

In [50]:
movies.columns

Index(['genres', 'keywords', 'original_language', 'original_title', 'overview',
       'popularity', 'production_companies', 'production_countries',
       'release_date', 'runtime', 'spoken_languages', 'status', 'title',
       'vote_average', 'vote_count', 'cast', 'crew'],
      dtype='object')

In [51]:
movies.shape

(4805, 17)

In [52]:
movies = movies[
    [
        "title",
        "overview",
        "genres",
        "keywords",
        "cast",
        "crew"
    ]
]

In [53]:
movies.head()

,title,overview,genres,keywords,cast,crew
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [54]:
movies.shape

(4805, 6)

In [55]:
#import ast

#obj = ast.literal_eval(
  #  movies.iloc[0]["genres"]
#)

In [56]:
#names = []
#for i in obj:
#
 #   names.append(i["name"])
#
 #   print(names)

In [57]:
import ast
def extracted_feature(text):

    L=[]
    text = ast.literal_eval(text)            # convert this : "[{'id':28,'name':'Science Fiction'}]"
    for i in text:                                  # to this : ['ScienceFiction']
    

        L.append(i["name"].replace(" ",""))

     


    return L

In [58]:
movies["genres"] = movies["genres"].apply(extracted_feature)

movies["keywords"] = movies["keywords"].apply(extracted_feature)

movies["cast"] = movies["cast"].apply(extracted_feature)

In [59]:
movies.head()

,title,overview,genres,keywords,cast,crew
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [60]:
movies.cast

0       [SamWorthington, ZoeSaldana, SigourneyWeaver, ...
1       [JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...
2       [DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...
3       [ChristianBale, MichaelCaine, GaryOldman, Anne...
4       [TaylorKitsch, LynnCollins, SamanthaMorton, Wi...
                              ...
4800    [CarlosGallardo, JaimedeHoyos, PeterMarquardt,...
4801    [EdwardBurns, KerryBishé, MarshaDietlein, Cait...
4802    [EricMabius, KristinBooth, CrystalLowe, GeoffG...
4803    [DanielHenney, ElizaCoupe, BillPaxton, AlanRuc...
4804    [DrewBarrymore, BrianHerzlinger, CoreyFeldman,...
Name: cast, Length: 4805, dtype: object

In [61]:
movies.crew

0       [{"credit_id": "52fe48009251416c750aca23", "de...
1       [{"credit_id": "52fe4232c3a36847f800b579", "de...
2       [{"credit_id": "54805967c3a36829b5002c41", "de...
3       [{"credit_id": "52fe4781c3a36847f81398c3", "de...
4       [{"credit_id": "52fe479ac3a36847f813eaa3", "de...
                              ...
4800    [{"credit_id": "52fe44eec3a36847f80b280b", "de...
4801    [{"credit_id": "52fe487dc3a368484e0fb013", "de...
4802    [{"credit_id": "52fe4df3c3a36847f8275ecf", "de...
4803    [{"credit_id": "52fe4ad9c3a368484e16a36b", "de...
4804    [{"credit_id": "58ce021b9251415a390165d9", "de...
Name: crew, Length: 4805, dtype: object

In [62]:
ast.literal_eval(
    movies.iloc[0]["crew"]
)

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  'gender': 2,
  'id': 2710,
  'job': 'Director',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750ac9d9',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Writer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca17',
  'department': 'Editing',
  'gender': 2,
  'id': 2710,
  'job': 'Editor',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca29',
  'department': 'Production',
  'gender': 2,
  'id': 2710,
  'job': 'Producer',
  'name': 'James Cameron'},
 {'credit_id': '52fe48009251416c750aca3f',
  'department': 'Writing',
  'gender': 2,
  'id': 2710,
  'job': 'Screenplay',
  'name': 'James Cameron'},
 {'credit_id': '539c4987c3a36810ba0021a4',
  'department': 'Art',
  'gender': 2,
  'id': 7236,
  'job': 'Art Direction',
  'name': 'Andrew Menzies'},
 {'credit_id': '549598c3c3a3686ae9004383',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 6690,
  'job': 'Visual Effects Producer',
  'name': 'Jill Brooks'},
 {'credit_id': '52fe48009251416c750aca4b',
  'department': 'Production',
  'gender': 1,
  'id': 6347,
  'job': 'Casting',
  'name': 'Margery Simkin'},
 {'credit_id': '570b6f419251417da70032fe',
  'department': 'Art',
  'gender': 2,
  'id': 6878,
  'job': 'Supervising Art Director',
  'name': 'Kevin Ishioka'},
 {'credit_id': '5495a0fac3a3686ae9004468',
  'department': 'Sound',
  'gender': 0,
  'id': 6883,
  'job': 'Music Editor',
  'name': 'Dick Bernstein'},
 {'credit_id': '54959706c3a3686af3003e81',
  'department': 'Sound',
  'gender': 0,
  'id': 8159,
  'job': 'Sound Effects Editor',
  'name': 'Shannon Mills'},
 {'credit_id': '54491d58c3a3680fb1001ccb',
  'department': 'Sound',
  'gender': 0,
  'id': 8160,
  'job': 'Foley',
  'name': 'Dennie Thorpe'},
 {'credit_id': '54491d6cc3a3680fa5001b2c',
  'department': 'Sound',
  'gender': 0,
  'id': 8163,
  'job': 'Foley',
  'name': 'Jana Vance'},
 {'credit_id': '52fe48009251416c750aca57',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 8527,
  'job': 'Costume Design',
  'name': 'Deborah Lynn Scott'},
 {'credit_id': '52fe48009251416c750aca2f',
  'department': 'Production',
  'gender': 2,
  'id': 8529,
  'job': 'Producer',
  'name': 'Jon Landau'},
 {'credit_id': '539c4937c3a36810ba002194',
  'department': 'Art',
  'gender': 0,
  'id': 9618,
  'job': 'Art Direction',
  'name': 'Sean Haworth'},
 {'credit_id': '539c49b6c3a36810c10020e6',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Set Decoration',
  'name': 'Kim Sinclair'},
 {'credit_id': '570b6f2f9251413a0e00020d',
  'department': 'Art',
  'gender': 1,
  'id': 12653,
  'job': 'Supervising Art Director',
  'name': 'Kim Sinclair'},
 {'credit_id': '54491a6c0e0a26748c001b19',
  'department': 'Art',
  'gender': 2,
  'id': 14350,
  'job': 'Set Designer',
  'name': 'Richard F. Mays'},
 {'credit_id': '56928cf4c3a3684cff0025c4',
  'department': 'Production',
  'gender': 1,
  'id': 20294,
  'job': 'Executive Producer',
  'name': 'Laeta Kalogridis'},
 {'credit_id': '52fe48009251416c750aca51',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 17675,
  'job': 'Costume Design',
  'name': 'Mayes C. Rubeo'},
 {'credit_id': '52fe48009251416c750aca11',
  'department': 'Camera',
  'gender': 2,
  'id': 18265,
  'job': 'Director of Photography',
  'name': 'Mauro Fiore'},
 {'credit_id': '5449194d0e0a26748f001b39',
  'department': 'Art',
  'gender': 0,
  'id': 42281,
  'job': 'Set Designer',
  'name': 'Scott Herbertson'},
 {'credit_id': '52fe48009251416c750aca05',
  'department': 'Crew',
  'gender': 0,
  'id': 42288,
  'job': 'Stunts',
  'name': 'Woody Schultz'},
 {'credit_id': '5592aefb92514152de0010f5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Makeup Artist',
  'name': 'Linda DeVetta'},
 {'credit_id': '5592afa492514152de00112c',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 29067,
  'job': 'Hairstylist',
  'name': 'Linda DeVetta'},
 {'credit_id': '54959ed592514130fc002e5d',
  'department': 'Camera',
  'gender': 2,
  'id': 33302,
  'job': 'Camera Operator',
  'name': 'Richard Bluck'},
 {'credit_id': '539c4891c3a36810ba002147',
  'department': 'Art',
  'gender': 2,
  'id': 33303,
  'job': 'Art Direction',
  'name': 'Simon Bright'},
 {'credit_id': '54959c069251417a81001f3a',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 113145,
  'job': 'Visual Effects Supervisor',
  'name': 'Richard Martin'},
 {'credit_id': '54959a0dc3a3680ff5002c8d',
  'department': 'Crew',
  'gender': 2,
  'id': 58188,
  'job': 'Visual Effects Editor',
  'name': 'Steve R. Moore'},
 {'credit_id': '52fe48009251416c750aca1d',
  'department': 'Editing',
  'gender': 2,
  'id': 58871,
  'job': 'Editor',
  'name': 'John Refoua'},
 {'credit_id': '54491a4dc3a3680fc30018ca',
  'department': 'Art',
  'gender': 0,
  'id': 92359,
  'job': 'Set Designer',
  'name': 'Karl J. Martin'},
 {'credit_id': '52fe48009251416c750aca35',
  'department': 'Camera',
  'gender': 1,
  'id': 72201,
  'job': 'Director of Photography',
  'name': 'Chiling Lin'},
 {'credit_id': '52fe48009251416c750ac9ff',
  'department': 'Crew',
  'gender': 0,
  'id': 89714,
  'job': 'Stunts',
  'name': 'Ilram Choi'},
 {'credit_id': '54959c529251416e2b004394',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 93214,
  'job': 'Visual Effects Supervisor',
  'name': 'Steven Quale'},
 {'credit_id': '54491edf0e0a267489001c37',
  'department': 'Crew',
  'gender': 1,
  'id': 122607,
  'job': 'Dialect Coach',
  'name': 'Carla Meyer'},
 {'credit_id': '539c485bc3a368653d001a3a',
  'department': 'Art',
  'gender': 2,
  'id': 132585,
  'job': 'Art Direction',
  'name': 'Nick Bassett'},
 {'credit_id': '539c4903c3a368653d001a74',
  'department': 'Art',
  'gender': 0,
  'id': 132596,
  'job': 'Art Direction',
  'name': 'Jill Cormack'},
 {'credit_id': '539c4967c3a368653d001a94',
  'department': 'Art',
  'gender': 0,
  'id': 132604,
  'job': 'Art Direction',
  'name': 'Andy McLaren'},
 {'credit_id': '52fe48009251416c750aca45',
  'department': 'Crew',
  'gender': 0,
  'id': 236696,
  'job': 'Motion Capture Artist',
  'name': 'Terry Notary'},
 {'credit_id': '54959e02c3a3680fc60027d2',
  'department': 'Crew',
  'gender': 2,
  'id': 956198,
  'job': 'Stunt Coordinator',
  'name': 'Garrett Warren'},
 {'credit_id': '54959ca3c3a3686ae300438c',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 957874,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Rothbart'},
 {'credit_id': '570b6f519251412c74001b2f',
  'department': 'Art',
  'gender': 0,
  'id': 957889,
  'job': 'Supervising Art Director',
  'name': 'Stefan Dechant'},
 {'credit_id': '570b6f62c3a3680b77007460',
  'department': 'Art',
  'gender': 2,
  'id': 959555,
  'job': 'Supervising Art Director',
  'name': 'Todd Cherniawsky'},
 {'credit_id': '539c4a3ac3a36810da0021cc',
  'department': 'Production',
  'gender': 0,
  'id': 1016177,
  'job': 'Casting',
  'name': 'Miranda Rivers'},
 {'credit_id': '539c482cc3a36810c1002062',
  'department': 'Art',
  'gender': 0,
  'id': 1032536,
  'job': 'Production Design',
  'name': 'Robert Stromberg'},
 {'credit_id': '539c4b65c3a36810c9002125',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1071680,
  'job': 'Costume Design',
  'name': 'John Harding'},
 {'credit_id': '54959e6692514130fc002e4e',
  'department': 'Camera',
  'gender': 0,
  'id': 1177364,
  'job': 'Steadicam Operator',
  'name': 'Roberto De Angelis'},
 {'credit_id': '539c49f1c3a368653d001aac',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 1202850,
  'job': 'Makeup Department Head',
  'name': 'Mike Smithson'},
 {'credit_id': '5495999ec3a3686ae100460c',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1204668,
  'job': 'Visual Effects Producer',
  'name': 'Alain Lalanne'},
 {'credit_id': '54959cdfc3a3681153002729',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1206410,
  'job': 'Visual Effects Supervisor',
  'name': 'Lucas Salton'},
 {'credit_id': '549596239251417a81001eae',
  'department': 'Crew',
  'gender': 0,
  'id': 1234266,
  'job': 'Post Production Supervisor',
  'name': 'Janace Tashjian'},
 {'credit_id': '54959c859251416e1e003efe',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1271932,
  'job': 'Visual Effects Supervisor',
  'name': 'Stephen Rosenbaum'},
 {'credit_id': '5592af28c3a368775a00105f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1310064,
  'job': 'Makeup Artist',
  'name': 'Frankie Karena'},
 {'credit_id': '539c4adfc3a36810e300203b',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 1319844,
  'job': 'Costume Supervisor',
  'name': 'Lisa Lovaas'},
 {'credit_id': '54959b579251416e2b004371',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1327028,
  'job': 'Visual Effects Supervisor',
  'name': 'Jonathan Fawkner'},
 {'credit_id': '539c48a7c3a36810b5001fa7',
  'department': 'Art',
  'gender': 0,
  'id': 1330561,
  'job': 'Art Direction',
  'name': 'Robert Bavin'},
 {'credit_id': '539c4a71c3a36810da0021e0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330567,
  'job': 'Costume Supervisor',
  'name': 'Anthony Almaraz'},
 {'credit_id': '539c4a8ac3a36810ba0021e4',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330570,
  'job': 'Costume Supervisor',
  'name': 'Carolyn M. Fenton'},
 {'credit_id': '539c4ab6c3a36810da0021f0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1330574,
  'job': 'Costume Supervisor',
  'name': 'Beth Koenigsberg'},
 {'credit_id': '54491ab70e0a267480001ba2',
  'department': 'Art',
  'gender': 0,
  'id': 1336191,
  'job': 'Set Designer',
  'name': 'Sam Page'},
 {'credit_id': '544919d9c3a3680fc30018bd',
  'department': 'Art',
  'gender': 0,
  'id': 1339441,
  'job': 'Set Designer',
  'name': 'Tex Kadonaga'},
 {'credit_id': '54491cf50e0a267483001b0c',
  'department': 'Editing',
  'gender': 0,
  'id': 1352422,
  'job': 'Dialogue Editor',
  'name': 'Kim Foscato'},
 {'credit_id': '544919f40e0a26748c001b09',
  'department': 'Art',
  'gender': 0,
  'id': 1352962,
  'job': 'Set Designer',
  'name': 'Tammy S. Lee'},
 {'credit_id': '5495a115c3a3680ff5002d71',
  'department': 'Crew',
  'gender': 0,
  'id': 1357070,
  'job': 'Transportation Coordinator',
  'name': 'Denny Caira'},
 {'credit_id': '5495a12f92514130fc002e94',
  'department': 'Crew',
  'gender': 0,
  'id': 1357071,
  'job': 'Transportation Coordinator',
  'name': 'James Waitkus'},
 {'credit_id': '5495976fc3a36811530026b0',
  'department': 'Sound',
  'gender': 0,
  'id': 1360103,
  'job': 'Supervising Sound Editor',
  'name': 'Addison Teague'},
 {'credit_id': '54491837c3a3680fb1001c5a',
  'department': 'Art',
  'gender': 2,
  'id': 1376887,
  'job': 'Set Designer',
  'name': 'C. Scott Baker'},
 {'credit_id': '54491878c3a3680fb4001c9d',
  'department': 'Art',
  'gender': 0,
  'id': 1376888,
  'job': 'Set Designer',
  'name': 'Luke Caska'},
 {'credit_id': '544918dac3a3680fa5001ae0',
  'department': 'Art',
  'gender': 0,
  'id': 1376889,
  'job': 'Set Designer',
  'name': 'David Chow'},
 {'credit_id': '544919110e0a267486001b68',
  'department': 'Art',
  'gender': 0,
  'id': 1376890,
  'job': 'Set Designer',
  'name': 'Jonathan Dyer'},
 {'credit_id': '54491967c3a3680faa001b5e',
  'department': 'Art',
  'gender': 0,
  'id': 1376891,
  'job': 'Set Designer',
  'name': 'Joseph Hiura'},
 {'credit_id': '54491997c3a3680fb1001c8a',
  'department': 'Art',
  'gender': 0,
  'id': 1376892,
  'job': 'Art Department Coordinator',
  'name': 'Rebecca Jellie'},
 {'credit_id': '544919ba0e0a26748f001b42',
  'department': 'Art',
  'gender': 0,
  'id': 1376893,
  'job': 'Set Designer',
  'name': 'Robert Andrew Johnson'},
 {'credit_id': '54491b1dc3a3680faa001b8c',
  'department': 'Art',
  'gender': 0,
  'id': 1376895,
  'job': 'Assistant Art Director',
  'name': 'Mike Stassi'},
 {'credit_id': '54491b79c3a3680fbb001826',
  'department': 'Art',
  'gender': 0,
  'id': 1376897,
  'job': 'Construction Coordinator',
  'name': 'John Villarino'},
 {'credit_id': '54491baec3a3680fb4001ce6',
  'department': 'Art',
  'gender': 2,
  'id': 1376898,
  'job': 'Assistant Art Director',
  'name': 'Jeffrey Wisniewski'},
 {'credit_id': '54491d2fc3a3680fb4001d07',
  'department': 'Editing',
  'gender': 0,
  'id': 1376899,
  'job': 'Dialogue Editor',
  'name': 'Cheryl Nardi'},
 {'credit_id': '54491d86c3a3680fa5001b2f',
  'department': 'Editing',
  'gender': 0,
  'id': 1376901,
  'job': 'Dialogue Editor',
  'name': 'Marshall Winn'},
 {'credit_id': '54491d9dc3a3680faa001bb0',
  'department': 'Sound',
  'gender': 0,
  'id': 1376902,
  'job': 'Supervising Sound Editor',
  'name': 'Gwendolyn Yates Whittle'},
 {'credit_id': '54491dc10e0a267486001bce',
  'department': 'Sound',
  'gender': 0,
  'id': 1376903,
  'job': 'Sound Re-Recording Mixer',
  'name': 'William Stein'},
 {'credit_id': '54491f500e0a26747c001c07',
  'department': 'Crew',
  'gender': 0,
  'id': 1376909,
  'job': 'Choreographer',
  'name': 'Lula Washington'},
 {'credit_id': '549599239251412c4e002a2e',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1391692,
  'job': 'Visual Effects Producer',
  'name': 'Chris Del Conte'},
 {'credit_id': '54959d54c3a36831b8001d9a',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1391695,
  'job': 'Visual Effects Supervisor',
  'name': 'R. Christopher White'},
 {'credit_id': '54959bdf9251412c4e002a66',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394070,
  'job': 'Visual Effects Supervisor',
  'name': 'Dan Lemmon'},
 {'credit_id': '5495971d92514132ed002922',
  'department': 'Sound',
  'gender': 0,
  'id': 1394129,
  'job': 'Sound Effects Editor',
  'name': 'Tim Nielsen'},
 {'credit_id': '5592b25792514152cc0011aa',
  'department': 'Crew',
  'gender': 0,
  'id': 1394286,
  'job': 'CG Supervisor',
  'name': 'Michael Mulholland'},
 {'credit_id': '54959a329251416e2b004355',
  'department': 'Crew',
  'gender': 0,
  'id': 1394750,
  'job': 'Visual Effects Editor',
  'name': 'Thomas Nittmann'},
 {'credit_id': '54959d6dc3a3686ae9004401',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1394755,
  'job': 'Visual Effects Supervisor',
  'name': 'Edson Williams'},
 {'credit_id': '5495a08fc3a3686ae300441c',
  'department': 'Editing',
  'gender': 0,
  'id': 1394953,
  'job': 'Digital Intermediate',
  'name': 'Christine Carr'},
 {'credit_id': '55402d659251413d6d000249',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1395269,
  'job': 'Visual Effects Supervisor',
  'name': 'John Bruno'},
 {'credit_id': '54959e7b9251416e1e003f3e',
  'department': 'Camera',
  'gender': 0,
  'id': 1398970,
  'job': 'Steadicam Operator',
  'name': 'David Emmerichs'},
 {'credit_id': '54959734c3a3686ae10045e0',
  'department': 'Sound',
  'gender': 0,
  'id': 1400906,
  'job': 'Sound Effects Editor',
  'name': 'Christopher Scarabosio'},
 {'credit_id': '549595dd92514130fc002d79',
  'department': 'Production',
  'gender': 0,
  'id': 1401784,
  'job': 'Production Supervisor',
  'name': 'Jennifer Teves'},
 {'credit_id': '549596009251413af70028cc',
  'department': 'Production',
  'gender': 0,
  'id': 1401785,
  'job': 'Production Manager',
  'name': 'Brigitte Yorke'},
 {'credit_id': '549596e892514130fc002d99',
  'department': 'Sound',
  'gender': 0,
  'id': 1401786,
  'job': 'Sound Effects Editor',
  'name': 'Ken Fischer'},
 {'credit_id': '549598229251412c4e002a1c',
  'department': 'Crew',
  'gender': 0,
  'id': 1401787,
  'job': 'Special Effects Coordinator',
  'name': 'Iain Hutton'},
 {'credit_id': '549598349251416e2b00432b',
  'department': 'Crew',
  'gender': 0,
  'id': 1401788,
  'job': 'Special Effects Coordinator',
  'name': 'Steve Ingram'},
 {'credit_id': '54959905c3a3686ae3004324',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401789,
  'job': 'Visual Effects Producer',
  'name': 'Joyce Cox'},
 {'credit_id': '5495994b92514132ed002951',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401790,
  'job': 'Visual Effects Producer',
  'name': 'Jenny Foster'},
 {'credit_id': '549599cbc3a3686ae1004613',
  'department': 'Crew',
  'gender': 0,
  'id': 1401791,
  'job': 'Visual Effects Editor',
  'name': 'Christopher Marino'},
 {'credit_id': '549599f2c3a3686ae100461e',
  'department': 'Crew',
  'gender': 0,
  'id': 1401792,
  'job': 'Visual Effects Editor',
  'name': 'Jim Milton'},
 {'credit_id': '54959a51c3a3686af3003eb5',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401793,
  'job': 'Visual Effects Producer',
  'name': 'Cyndi Ochs'},
 {'credit_id': '54959a7cc3a36811530026f4',
  'department': 'Crew',
  'gender': 0,
  'id': 1401794,
  'job': 'Visual Effects Editor',
  'name': 'Lucas Putnam'},
 {'credit_id': '54959b91c3a3680ff5002cb4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401795,
  'job': 'Visual Effects Supervisor',
  'name': "Anthony 'Max' Ivins"},
 {'credit_id': '54959bb69251412c4e002a5f',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401796,
  'job': 'Visual Effects Supervisor',
  'name': 'John Knoll'},
 {'credit_id': '54959cbbc3a3686ae3004391',
  'department': 'Visual Effects',
  'gender': 2,
  'id': 1401799,
  'job': 'Visual Effects Supervisor',
  'name': 'Eric Saindon'},
 {'credit_id': '54959d06c3a3686ae90043f6',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401800,
  'job': 'Visual Effects Supervisor',
  'name': 'Wayne Stables'},
 {'credit_id': '54959d259251416e1e003f11',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401801,
  'job': 'Visual Effects Supervisor',
  'name': 'David Stinnett'},
 {'credit_id': '54959db49251413af7002975',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401803,
  'job': 'Visual Effects Supervisor',
  'name': 'Guy Williams'},
 {'credit_id': '54959de4c3a3681153002750',
  'department': 'Crew',
  'gender': 0,
  'id': 1401804,
  'job': 'Stunt Coordinator',
  'name': 'Stuart Thorp'},
 {'credit_id': '54959ef2c3a3680fc60027f2',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401805,
  'job': 'Best Boy Electric',
  'name': 'Giles Coburn'},
 {'credit_id': '54959f07c3a3680fc60027f9',
  'department': 'Camera',
  'gender': 2,
  'id': 1401806,
  'job': 'Still Photographer',
  'name': 'Mark Fellman'},
 {'credit_id': '54959f47c3a3681153002774',
  'department': 'Lighting',
  'gender': 0,
  'id': 1401807,
  'job': 'Lighting Technician',
  'name': 'Scott Sprague'},
 {'credit_id': '54959f8cc3a36831b8001df2',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401808,
  'job': 'Animation Director',
  'name': 'Jeremy Hollobon'},
 {'credit_id': '54959fa0c3a36831b8001dfb',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401809,
  'job': 'Animation Director',
  'name': 'Orlando Meunier'},
 {'credit_id': '54959fb6c3a3686af3003f54',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1401810,
  'job': 'Animation Director',
  'name': 'Taisuke Tanimura'},
 {'credit_id': '54959fd2c3a36831b8001e02',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1401812,
  'job': 'Set Costumer',
  'name': 'Lilia Mishel Acevedo'},

In [63]:
def extracted_crew(text):

    L = []

    text = ast.literal_eval(text)

    for i in text:

        if i["job"] == "Director":

          L.append(i["name"].replace(" ",""))

        

    return L

In [64]:
movies["crew"] = movies["crew"].apply(extracted_crew)

In [65]:
movies.head()

,title,overview,genres,keywords,cast,crew
0,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [66]:
def split_overview(text):

    return text.split()

In [67]:
movies["overview"] = movies["overview"].apply(split_overview)

In [68]:
movies.head()

,title,overview,genres,keywords,cast,crew
0,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes]
3,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [69]:
movies["tags"] = (
    movies["overview"]
    + movies["genres"]
    + movies["keywords"]
    + movies["cast"]
    + movies["crew"]
)

In [70]:
movies.iloc[0]["tags"]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'StephenLang',
 'MichelleRodriguez',
 'GiovanniRibisi',
 'JoelDavidMoore',
 'CCHPounder',
 'WesStudi',
 'LazAlonso',
 'DileepRao',
 'MattGerald',
 'SeanAnthonyMoran',
 'JasonWhyte',
 'ScottLawrence',
 'KellyKilgour',
 'JamesPatrickPitt',
 'SeanPatrickMurphy',
 'PeterDillon',
 'KevinDorman',
 'KelsonHenderson',
 'DavidVanHorn',
 'JacobTomuri',
 'MichaelBlain-Rozgay',
 'JonCurry',
 'LukeHawker',
 'WoodySchultz',
 'PeterMensah',
 'SoniaYee',
 'JahnelCurfman',
 'IlramChoi',
 'KylaWarren',
 'LisaRoumain',
 'DebraWilson',
 'ChrisMala',
 'TaylorKibby',
 'JodieLandau',
 'JulieLamm',
 'CullenB.Madden',
 'JosephBradyMadden',
 'FrankieTorres',
 'AustinWilson',
 'SaraWilson',
 'TamicaWashington-Miller',
 'LucyBriant',
 'NathanMeister',
 'GerryBlair',
 'MatthewChamberlain',
 'PaulYates',
 'WrayWilson',
 'JamesGaylyn',
 'MelvinLenoClarkIII',
 'CarvonFutrell',
 'BrandonJelkes',
 'MicahMoch',
 'HanniyahMuhammad',
 'ChristopherNolen',
 'ChristaOliver',
 'AprilMarieThomas',
 'BravitaA.Threatt',
 'ColinBleasdale',
 'MikeBodnar',
 'MattClayton',
 'NicoleDionne',
 'JamieHarrison',
 'AllanHenry',
 'AnthonyIngruber',
 'AshleyJeffery',
 'DeanKnowsley',
 'JosephMika-Hunt',
 'TerryNotary',
 'KaiPantano',
 'LoganPithyou',
 'StuartPollock',
 'Raja',
 'GarethRuck',
 'RhianSheehan',
 'T.J.Storm',
 'JodieTaylor',
 'AliciaVela-Bailey',
 'RichardWhiteside',
 'NikieZambo',
 'JuleneRenee',
 'JamesCameron']

In [71]:
movies["tags"] = movies["tags"].apply(lambda x: " ".join(x))

In [72]:
movies.iloc[0]["tags"]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez GiovanniRibisi JoelDavidMoore CCHPounder WesStudi LazAlonso DileepRao MattGerald SeanAnthonyMoran JasonWhyte ScottLawrence KellyKilgour JamesPatrickPitt SeanPatrickMurphy PeterDillon KevinDorman KelsonHenderson DavidVanHorn JacobTomuri MichaelBlain-Rozgay JonCurry LukeHawker WoodySchultz PeterMensah SoniaYee JahnelCurfman IlramChoi KylaWarren LisaRoumain DebraWilson ChrisMala TaylorKibby JodieLandau JulieLamm CullenB.Madden JosephBradyMadden FrankieTorres AustinWilson SaraWilson TamicaWashington-Miller LucyBriant NathanMeister GerryBlair MatthewChamberlain PaulYates WrayWilson JamesGaylyn MelvinLenoClarkIII CarvonFutrell BrandonJelkes MicahMoch HanniyahMuhammad ChristopherNolen ChristaOliver AprilMarieThomas BravitaA.Threatt ColinBleasdale MikeBodnar MattClayton NicoleDionne JamieHarrison AllanHenry AnthonyIngruber AshleyJeffery DeanKnowsley JosephMika-Hunt TerryNotary KaiPantano LoganPithyou StuartPollock Raja GarethRuck RhianSheehan T.J.Storm JodieTaylor AliciaVela-Bailey RichardWhiteside NikieZambo JuleneRenee JamesCameron'

In [73]:
movies.head()

,title,overview,genres,keywords,cast,crew,tags
0,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux, Ralp...",[SamMendes],A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],Following the death of District Attorney Harve...
4,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"John Carter is a war-weary, former military ca..."

In [74]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(
    max_features=5000,
    stop_words="english"
)

vectors = cv.fit_transform(movies["tags"]).toarray()

In [75]:
vectors.shape

(4805, 5000)

In [76]:
from sklearn.metrics.pairwise import cosine_similarity

similaritys = cosine_similarity(vectors)

In [77]:
similaritys.shape

(4805, 4805)

In [78]:
movie_list = list(enumerate(similaritys[0]))

In [79]:
sorted_movies = sorted(
    movie_list,
    reverse=True,
    key=lambda x: x[1]
)

In [80]:
sorted_movies

[(0, 1.0000000000000007),
 (1916, 0.23473823893078544),
 (1214, 0.23294541397390256),
 (582, 0.23097828906119441),
 (539, 0.2252817784447915),
 (507, 0.2191252450446388),
 (3606, 0.21606790785072144),
 (1440, 0.21398024625545647),
 (4190, 0.2123976976214366),
 (260, 0.21170244960998522),
 (74, 0.20935894733965596),
 (83, 0.20256711147285467),
 (2969, 0.19839002137983244),
 (3728, 0.19738550848793068),
 (495, 0.19304683562633607),
 (2329, 0.19258222162991084),
 (322, 0.1904761904761905),
 (61, 0.1889822365046136),
 (36, 0.18824832213400472),
 (1202, 0.18824832213400472),
 (2405, 0.18609684207969418),
 (1192, 0.18523964340873708),
 (1533, 0.18523964340873708),
 (2200, 0.18257418583505536),
 (3536, 0.18257418583505536),
 (973, 0.18257418583505533),
 (3325, 0.18184824186332701),
 (2782, 0.18156825980064073),
 (972, 0.1800205749557739),
 (4405, 0.17817416127494962),
 (47, 0.1781741612749496),
 (1319, 0.17699808135119716),
 (4046, 0.17636890537566463),
 (1327, 0.17496355305594127),
 (942, 0.17295817388759027),
 (151, 0.17251638983558856),
 (3160, 0.1711841970043652),
 (2997, 0.17118419700436519),
 (184, 0.17078251276599332),
 (466, 0.1690308509457033),
 (2727, 0.1683587574253685),
 (150, 0.16718346377260584),
 (27, 0.1649572197684645),
 (305, 0.1648119469795901),
 (461, 0.16448792373994223),
 (220, 0.16366341767699427),
 (1342, 0.16366341767699427),
 (301, 0.16143660075018942),
 (1273, 0.16116459280507608),
 (4, 0.16101529717988267),
 (158, 0.16070868073806158),
 (1669, 0.15936381457791915),
 (581, 0.15748519708717804),
 (931, 0.1564921592871903),
 (300, 0.15590239111558093),
 (1069, 0.15590239111558093),
 (4008, 0.1543033499620919),
 (46, 0.15275252316519466),
 (1199, 0.1522038868295523),
 (661, 0.15194743527951726),
 (373, 0.15130688316720062),
 (1392, 0.151247535495505),
 (1827, 0.151247535495505),
 (838, 0.14969623771302396),
 (3352, 0.14847846772912465),
 (3620, 0.14824986333222023),
 (108, 0.1469861839480328),
 (1941, 0.14638501094227999),
 (208, 0.1454785934906616),
 (502, 0.14458880781356398),
 (1379, 0.14458880781356398),
 (2492, 0.1432670637653132),
 (2511, 0.1432670637653132),
 (3626, 0.1432670637653132),
 (4336, 0.14285714285714288),
 (56, 0.14085904245475275),
 (1961, 0.14062009564580388),
 (149, 0.13977131156292244),
 (168, 0.13957263155977062),
 (1804, 0.13957263155977062),
 (2071, 0.13856849886842332),
 (2165, 0.13856849886842332),
 (7, 0.13829563644637993),
 (1353, 0.13801311186847084),
 (1218, 0.136504726557987),
 (1934, 0.136504726557987),
 (1176, 0.13638618139749523),
 (1484, 0.13468700594029479),
 (2968, 0.13468700594029479),
 (139, 0.13397282541141675),
 (91, 0.13231403100624078),
 (577, 0.13231403100624078),
 (332, 0.13231403100624076),
 (2682, 0.13231403100624076),
 (67, 0.13226001425322162),
 (311, 0.13226001425322162),
 (84, 0.13195808169029696),
 (490, 0.1315903389919538),
 (1325, 0.1315903389919538),
 (3997, 0.1315903389919538),
 (26, 0.13093073414159542),
 (1295, 0.13093073414159542),
 (1320, 0.13093073414159542),
 (17, 0.130031582934249),
 (2580, 0.1286978904175574),
 (31, 0.12858612496840993),
 (568, 0.12858612496840993),
 (687, 0.12858612496840993),
 (1297, 0.12858612496840993),
 (2129, 0.12717117101978923),
 (41, 0.12598815766974242),
 (206, 0.12598815766974242),
 (422, 0.12598815766974242),
 (487, 0.12598815766974242),
 (2616, 0.12598815766974242),
 (557, 0.12515654358043973),
 (3407, 0.12515654358043973),
 (2869, 0.12483755678647186),
 (127, 0.12389865694583801),
 (1711, 0.12371791482634838),
 (413, 0.1235415527768502),
 (595, 0.1235415527768502),
 (505, 0.12344267996967355),
 (4490, 0.12344267996967355),
 (342, 0.12309149097933272),
 (157, 0.12104550653376049),
 (1045, 0.12104550653376049),
 (1743, 0.12104550653376049),
 (2374, 0.12104550653376049),
 (3671, 0.12049067317796998),
 (2476, 0.11952286093343936),
 (454, 0.11904761904761905),
 (1035, 0.11904761904761905),
 (368, 0.11878277418329973),
 (199, 0.11853911695403994),
 (111, 0.11765520133375293),
 (3405, 0.11765520133375293),
 (1737, 0.11757927025044307),
 (172, 0.11664236870396086),
 (939, 0.11664236870396086),
 (1000, 0.11664236870396086),
 (1654, 0.11664236870396084),
 (187, 0.11631052629980886),
 (4201, 0.11572751247156893),
 (4348, 0.11572751247156893),
 (94, 0.11501092655705904),
 (1013, 0.11501092655705904),
 (1613, 0.11501092655705904),
 (2709, 0.11501092655705904),
 (2864, 0.11461365101225056),
 (4672, 0.11461365101225056),
 (238, 0.11396057645963795),
 (228, 0.11375393879832252),
 (420, 0.11375393879832252),
 (249, 0.1126872339638022),
 (1829, 0.1126872339638022),
 (3374, 0.1126872339638022),
 (549, 0.11253728415158593),
 (740, 0.11253728415158593),
 (1828, 0.11135885079684353),
 (3307, 0.11135885079684353),
 (3628, 0.11135885079684353),
 (432, 0.11135885079684352),
 (50, 0.11085479909473867),
 (3145, 0.11065666703449763),
 (2543, 0.11021667854435135),
 (123, 0.11021667854435134),
 (270, 0.11021667854435134),
 (3659, 0.10910894511799621),
 (43, 0.1091089451179962),
 (778, 0.1091089451179962),
 (1275, 0.1091089451179962),
 (134, 0.10910894511799618),
 (1029, 0.10910894511799618),
 (1094, 0.10910894511799618),
 (1272, 0.10910894511799618),
 (1508, 0.10910894511799618),
 (4095, 0.10910894511799618),
 (232, 0.10744306187005072),
 (859, 0.10744306187005072),
 (52, 0.10699012312772824),
 (95, 0.10699012312772824),
 (1475, 0.10699012312772824),
 (1299, 0.1061988488107183),
 (1369, 0.1061988488107183),
 (1570, 0.1061988488107183),
 (2630, 0.1061988488107183),
 (4545, 0.10597597584982435),
 (28, 0.10585122480499261),
 (148, 0.10585122480499261),
 (544, 0.10585122480499261),
 (1271, 0.10585122480499261),
 (2435, 0.10499013139145202),
 (81, 0.10482848367219183),
 (483, 0.10432810619146021),
 (2446, 0.10432810619146021),
 (2579, 0.10432810619146021),
 (3496, 0.10432810619146021),
 (4077, 0.10432810619146021),
 (425, 0.10403129732205989),
 (2756, 0.10403129732205989),
 (627, 0.10350983390135313),
 (653, 0.10350983390135313),
 (808, 0.10350983390135313),
 (1154, 0.10350983390135313),
 (2517, 0.10350983390135313),
 (3719, 0.10350983390135313),
 (3998, 0.10350983390135313),
 (239, 0.10309826235529032),
 (777, 0.10309826235529032),
 (10, 0.10286889997472794),
 (87, 0.10286889997472794),
 (88, 0.10286889997472794),
 (160, 0.10286889997472794),
 (275, 0.10286889997472794),
 (746, 0.10286889997472794),
 (1292, 0.10286889997472794),
 (1978, 0.10286889997472794),
 (1017, 0.10218988991416098),
 (294, 0.10146925788636821),
 (579, 0.1014692578863682),
 (2068, 0.1014692578863682),
 (3100, 0.1014692578863682),
 (3618, 0.1014692578863682),
 (102, 0.10130511230913847),
 (692, 0.10130511230913847),
 (141, 0.10101525445522108),
 (2758, 0.10101525445522108),
 (3779, 0.10101525445522108),
 (4016, 0.10101525445522108),
 (4196, 0.10101525445522108),
 (18, 0.10044292546128848),
 (166, 0.10012523486435178),
 (1288, 0.10012523486435178),
 (1397, 0.10012523486435178),
 (2177, 0.10012523486435178),
 (3338, 0.10012523486435178),
 (169, 0.09960238411119947),
 (2102, 0.09960238411119947),
 (68, 0.09883324222148016),
 (122, 0.09883324222148016),
 (203, 0.09883324222148016),
 (266, 0.09883324222148016),
 (754, 0.09883324222148016),
 (854, 0.09883324222148016),
 (900, 0.09883324222148016),
 (986, 0.09883324222148016),
 (1080, 0.09883324222148016),
 (1173, 0.09883324222148016),
 (193, 0.09878259746169996),
 (773, 0.09869275424396534),
 (1520, 0.09869275424396534),
 (1717, 0.09869275424396534),
 (2255, 0.09869275424396534),
 (2319, 0.09869275424396534),
 (3837, 0.09869275424396534),
 (4331, 0.09869275424396534),
 (4622, 0.09869275424396534),
 (312, 0.09759000729485333),
 (535, 0.09759000729485333),
 (787, 0.09759000729485333),
 (1107, 0.09759000729485333),
 (2009, 0.09759000729485333),
 (3781, 0.09759000729485333),
 (4228, 0.09759000729485333),
 (213, 0.09720197391996738),
 (1723, 0.09652341781316803),
 (2657, 0.09652341781316803),
 (1084, 0.09639253854237599),
 (1156, 0.09639253854237599),
 (1193, 0.09639253854237599),
 (513, 0.09639253854237598),
 (153, 0.09569487529386911),
 (72, 0.09523809523809525),
 (131, 0.09523809523809525),
 (334, 0.09523809523809525),
 (1200, 0.09523809523809525),
 (1819, 0.09523809523809525),
 (3441, 0.09523809523809525),
 (3462, 0.09523809523809525),
 (2592, 0.09523809523809523),
 (624, 0.09449111825230681),
 (660, 0.09449111825230681),
 (1571, 0.09449111825230681),
 (2647, 0.09449111825230681),
 (3053, 0.09449111825230681),
 (3734, 0.09449111825230681),
 (14, 0.09412416106700235),
 (174, 0.09412416106700235),
 (295, 0.09412416106700235),
 (510, 0.09412416106700235),
 (3006, 0.09412416106700235),
 (2384, 0.09304842103984709),
 (371, 0.09304842103984708),
 (1054, 0.09304842103984708),
 (3138, 0.09304842103984708),
 (3091, 0.09258200997725516),
 (3952, 0.09258200997725516),
 (4254, 0.09258200997725516),
 (403, 0.09221388919541469),
 (785, 0.09221388919541468),
 (85, 0.09212254307176114),
 (307, 0.09212254307176114),
 (529, 0.09200874124564723),
 (5, 0.09156219276643894),
 (410, 0.09100315103865801),
 (508, 0.09100315103865801),
 (898, 0.09100315103865801),
 (1842, 0.09100315103865801),
 (1920, 0.09100315103865801),
 (715, 0.09078412990032037),
 (1075, 0.09078412990032037),
 (1278, 0.09078412990032037),
 (1497, 0.09078412990032037),
 (1585, 0.09078412990032037),
 (1682, 0.09078412990032037),
 (2452, 0.09078412990032037),
 (2558, 0.09078412990032037),
 (2648, 0.09078412990032037),
 (4133, 0.09078412990032037),
 (126, 0.09002982732126874),
 (933, 0.09002982732126874),
 (1231, 0.09002982732126874),
 (257, 0.08908708063747482),
 (278, 0.08908708063747482),
 (330, 0.08908708063747482),
 (643, 0.08908708063747482),
 (2280, 0.08908708063747482),
 (4043, 0.08908708063747482),
 (2792, 0.08908708063747481),
 (4640, 0.08908708063747481),
 (4653, 0.08908708063747481),
 (476, 0.0890870806374748),
 (479, 0.0890870806374748),
 (794, 0.0890870806374748),
 (922, 0.0890870806374748),
 (1404, 0.0890870806374748),
 (2656, 0.0890870806374748),
 (1087, 0.08849904067559858),
 (279, 0.08817334283548107),
 (412, 0.08817334283548107),
 (870, 0.08817334283548107),
 (2392, 0.08748177652797065),
 (564, 0.08748177652797064),
 (791, 0.08748177652797064),
 (937, 0.08748177652797064),
 (1304, 0.08748177652797064),
 (3295, 0.08748177652797064),
 (4468, 0.08748177652797064),
 (596, 0.08728715609439695),
 (813, 0.08728715609439695),
 (1028, 0.08728715609439695),
 (1355, 0.08642716314028859),
 (129, 0.08642716314028857),
 (182, 0.08642716314028857),
 (589, 0.08642716314028857),
 (995, 0.08642716314028857),
 (1276, 0.08642716314028857),
 (799, 0.08625819491779428),
 (292, 0.08596023825918792),
 (369, 0.08596023825918792),
 (389, 0.08596023825918792),
 (786, 0.08596023825918792),
 (935, 0.08596023825918792),
 (1470, 0.08596023825918792),
 (2089, 0.08596023825918792),
 (2243, 0.08596023825918792),
 (2813, 0.08596023825918792),
 (2836, 0.08596023825918792),
 (45, 0.08559209850218259),
 (253, 0.08559209850218259),
 (1435, 0.08559209850218259),
 (2270, 0.08559209850218259),
 (2484, 0.08559209850218259),
 (4516, 0.08559209850218259),
 (467, 0.08478078067985949),
 (607, 0.08478078067985949),
 (1999, 0.08478078067985949),
 (2001, 0.08478078067985949),
 (142, 0.08451542547285165),
 (167, 0.08451542547285165),
 (306, 0.08451542547285165),
 (356, 0.08451542547285165),
 (400, 0.08451542547285165),
 (960, 0.08451542547285165),
 (1752, 0.08451542547285165),
 (3426, 0.08451542547285165),
 (3535, 0.08451542547285165),
 (4625, 0.08451542547285165),
 (107, 0.08399210511316162),
 (222, 0.08399210511316162),
 (473, 0.08399210511316162),
 (243, 0.08322503785764791),
 (612, 0.08322503785764791),
 (2966, 0.08322503785764791),
 (233, 0.083141099321054),
 (315, 0.083141099321054),
 (781, 0.083141099321054),
 (901, 0.083141099321054),
 (1002, 0.083141099321054),
 (1582, 0.083141099321054),
 (2163, 0.083141099321054),
 (3814, 0.083141099321054),
 (3924, 0.083141099321054),
 (4257, 0.083141099321054),
 (92, 0.08247860988423225),
 (491, 0.08247860988423225),
 (1274, 0.08247860988423225),
 (3152, 0.08247860988423225),
 (3216, 0.08247860988423225),
 (4353, 0.08247860988423225),
 (4736, 0.08247860988423225),
 (164, 0.08183170883849714),
 (511, 0.08183170883849714),
 (920, 0.08183170883849714),
 (1374, 0.08183170883849714),
 (1519, 0.08183170883849714),
 (1556, 0.08183170883849714),
 (1696, 0.08183170883849714),
 (4656, 0.08183170883849714),
 (618, 0.08175191193132877),
 (1492, 0.08175191193132877),
 (1493, 0.08175191193132877),
 (1874, 0.08175191193132877),
 (1414, 0.08104408984731078),
 (1483, 0.08104408984731078),
 (2095, 0.08104408984731078),
 (3439, 0.08104408984731078),
 (35, 0.08058229640253804),
 (75, 0.08058229640253804),
 (263, 0.08058229640253804),
 (349, 0.08058229640253804),
 (691, 0.08058229640253804),
 (775, 0.08058229640253804),
 (978, 0.08058229640253804),
 (1247, 0.08058229640253804),
 (1786, 0.08058229640253804),
 (2247, 0.08058229640253804),
 (2249, 0.08058229640253804),
 (2790, 0.08058229640253804),
 (3026, 0.08058229640253804),
 (3299, 0.08058229640253804),
 (3308, 0.08058229640253804),
 (3421, 0.08058229640253804),
 (3908, 0.08058229640253804),
 (2382, 0.08043618151097337),
 (2444, 0.08043618151097337),
 (2494, 0.08035434036903079),
 (170, 0.07968190728895957),
 (768, 0.07968190728895957),
 (1824, 0.07968190728895957),
 (2876, 0.07968190728895957),
 (3251, 0.07968190728895957),
 (3429, 0.07968190728895957),
 (3947, 0.07968190728895957),
 (4059, 0.07968190728895957),
 (4492, 0.07968190728895957),
 (4502, 0.07968190728895957),
 (207, 0.07938841860374446),
 (236, 0.07938841860374446),
 (271, 0.07938841860374446),
 (325, 0.07938841860374446),
 (530, 0.07938841860374446),
 (814, 0.07938841860374446),
 (1140, 0.07938841860374446),
 (1205, 0.07938841860374446),
 (2640, 0.07938841860374446),
 (3233, 0.07938841860374446),
 (103, 0.07902607796935997),
 (812, 0.07902607796935997),
 (1280, 0.07902607796935997),
 (1344, 0.07902607796935997),
 (1401, 0.07902607796935997),
 (1894, 0.07902607796935997),
 (230, 0.07838618016696206),
 (1635, 0.07838618016696206),
 (23, 0.07824607964359516),
 (33, 0.07824607964359516),
 (112, 0.07824607964359516),
 (227, 0.07824607964359516),
 (241, 0.07824607964359516),
 (894, 0.07824607964359516),
 (1610, 0.07824607964359516),
 (1612, 0.07824607964359516),
 (2300, 0.07824607964359516),
 (32, 0.0777615791359739),
 (63, 0.0777615791359739),
 (363, 0.0777615791359739),
 (654, 0.0777615791359739),
 (12, 0.07715167498104596),
 (21, 0.07715167498104596),
 (51, 0.07715167498104596),
 (634, 0.07715167498104596),
 (1025, 0.07715167498104596),
 (1137, 0.07715167498104596),
 (1530, 0.07715167498104596),
 (2171, 0.07715167498104596),
 (2350, 0.07715167498104596),
 (2797, 0.07715167498104596),
 (2852, 0.07715167498104596),
 (3153, 0.07715167498104596),
 (3468, 0.07715167498104596),
 (3525, 0.07715167498104596),
 (4431, 0.07715167498104596),
 (4717, 0.07715167498104596),
 (19, 0.07655590023509529),
 (501, 0.07655590023509529),
 (572, 0.07655590023509529),
 (1922, 0.07655590023509529),
 (96, 0.07610194341477615),
 (214, 0.07610194341477615),
 (242, 0.07610194341477615),
 (680, 0.07610194341477615),
 (752, 0.07610194341477615),
 (985, 0.07610194341477615),
 (1111, 0.07610194341477615),
 (1938, 0.07610194341477615),
 (2523, 0.07610194341477615),
 (2847, 0.07610194341477615),
 (59, 0.07597371763975863),
 (2759, 0.07540461810874112),
 (245, 0.07509392614826384),
 (587, 0.07509392614826384),
 (1159, 0.07509392614826384),
 (1179, 0.07509392614826384),
 (1469, 0.07509392614826384),
 (2679, 0.07509392614826384),
 (2816, 0.07509392614826384),
 (3204, 0.07509392614826384),
 (3699, 0.07509392614826384),
 (4081, 0.07509392614826384),
 (125, 0.07493633116627259),
 (313, 0.07484811885651198),
 (2161, 0.07484811885651198),
 (2406, 0.07484811885651198),
 (2708, 0.07484811885651198),
 (2785, 0.07484811885651198),
 (3067, 0.07484811885651198),
 (274, 0.07458533939516852),
 (71, 0.07412493166611012),
 (98, 0.07412493166611012),
 (457, 0.07412493166611012),
 (885, 0.07412493166611012),
 (899, 0.07412493166611012),
 (1009, 0.07412493166611012),
 (1267, 0.07412493166611012),
 (1363, 0.07412493166611012),
 (2014, 0.07412493166611012),
 (3353, 0.07412493166611012),
 (3387, 0.07412493166611012),
 (2199, 0.07377111135633176),
 (70, 0.07319250547113999),
 (97, 0.07319250547113999),
 (223, 0.07319250547113999),
 (547, 0.07319250547113999),
 (632, 0.07319250547113999),
 (788, 0.07319250547113999),
 (2159, 0.07319250547113999),
 (2231, 0.07319250547113999),
 (2588, 0.07319250547113999),
 (2646, 0.07319250547113999),
 (3057, 0.07319250547113999),
 (4121, 0.07319250547113999),
 (415, 0.0727392967453308),
 (1286, 0.0727392967453308),
 (2246, 0.0727392967453308),
 (3830, 0.0727392967453308),
 (4163, 0.0727392967453308),
 (11, 0.07229440390678199),
 (39, 0.07229440390678199),
 (105, 0.07229440390678199),
 (185, 0.07229440390678199),
 (362, 0.07229440390678199),
 (503, 0.07229440390678199),
 (827, 0.07229440390678199),
 (3020, 0.07229440390678199),
 (3089, 0.07229440390678199),
 (3905, 0.07229440390678199),
 (4053, 0.07229440390678199),
 (4203, 0.07229440390678199),
 (4451, 0.07229440390678199),
 (4639, 0.07229440390678199),
 (190, 0.07174960033341753),
 (3366, 0.07174960033341753),
 (1, 0.07142857142857144),
 (53, 0.07142857142857144),
 (138, 0.07142857142857144),
 (472, 0.07142857142857144),
 (543, 0.07142857142857144),
 (1030, 0.07142857142857144),
 (2391, 0.07142857142857144),
 (2697, 0.07142857142857144),
 (3253, 0.07142857142857144),
 (3447, 0.07142857142857144),
 (3804, 0.07142857142857144),
 (4178, 0.07142857142857144),
 (381, 0.07079923254047886),
 (2880, 0.07079923254047886),
 (3372, 0.07079923254047886),
 (4412, 0.07079923254047886),
 (37, 0.07059312080025176),
 (212, 0.07059312080025176),
 (626, 0.07059312080025176),
 (1143, 0.07059312080025176),
 (2131, 0.07059312080025176),
 (1630, 0.07033799484533299),
 (82, 0.06978631577988531),
 (1287, 0.06978631577988531),
 (1323, 0.06978631577988531),
 (1442, 0.06978631577988531),
 (1879, 0.06978631577988531),
 (2048, 0.06978631577988531),
 (2237, 0.06978631577988531),
 (2260, 0.06978631577988531),
 (2463, 0.06978631577988531),
 (2827, 0.06978631577988531),
 (2914, 0.06978631577988531),
 (3388, 0.06978631577988531),
 (3820, 0.06978631577988531),
 (55, 0.06944193284588147),
 (229, 0.06944193284588147),
 (205, 0.06900655593423542),
 (471, 0.06900655593423542),
 (534, 0.06900655593423542),
 (536, 0.06900655593423542),
 (665, 0.06900655593423542),
 (671, 0.06900655593423542),
 (732, 0.06900655593423542),
 (908, 0.06900655593423542),
 (1003, 0.06900655593423542),
 (1346, 0.06900655593423542),
 (1617, 0.06900655593423542),
 (1619, 0.06900655593423542),
 (1628, 0.06900655593423542),
 (1660, 0.06900655593423542),
 (1761, 0.06900655593423542),
 (1766, 0.06900655593423542),
 (2017, 0.06900655593423542),
 (2783, 0.06900655593423542),
 (3396, 0.06900655593423542),
 (3980, 0.06900655593423542),
 (3992, 0.06900655593423542),
 (4179, 0.06900655593423542),
 (4473, 0.06900655593423542),
 (101, 0.0682523632789935),
 (728, 0.0682523632789935),
 (782, 0.0682523632789935),
 (3186, 0.0682523632789935),
 (4538, 0.0682523632789935),
 (488, 0.06774797209007694),
 (121, 0.06752237049095156),
 (132, 0.06752237049095156),
 (254, 0.06752237049095156),
 (977, 0.06752237049095156),
 (1144, 0.06752237049095156),
 (1697, 0.06752237049095156),
 (2052, 0.06752237049095156),
 (2359, 0.06752237049095156),
 (2886, 0.06752237049095156),
 (2998, 0.06752237049095156),
 (109, 0.06734350297014739),
 (384, 0.06734350297014739),
 (776, 0.06734350297014739),
 (1321, 0.06734350297014739),
 (1651, 0.06734350297014739),
 (1986, 0.06734350297014739),
 (2655, 0.06734350297014739),
 (3667, 0.06734350297014739),
 (3929, 0.06734350297014739),
 (4097, 0.06734350297014739),
 (4214, 0.06734350297014739),
 (4403, 0.06734350297014739),
 (4567, 0.06734350297014739),
 (4637, 0.06734350297014739),
 (657, 0.06694619270045785),
 (3210, 0.06689898654154956),
 (1189, 0.06681531047810611),
 (1451, 0.06681531047810611),
 (2368, 0.06681531047810611),
 (4343, 0.06681531047810611),
 (183, 0.06617222226472869),
 (76, 0.06613000712661081),

In [81]:
movies.iloc[1916].title

'Lifeforce'

In [82]:
for i in sorted_movies[1:6]:

    print(movies.iloc[i[0]].title)

Lifeforce
Aliens vs Predator: Requiem
Battle: Los Angeles
Titan A.E.
Independence Day

In [83]:
def recommend(movie):

    movie_index = movies[movies["title"] == movie].index[0]

    distance = similaritys[movie_index]

    movie_list = list(enumerate(distance))

    sorted_movies = sorted(
        movie_list,
        reverse=True,
        key=lambda x: x[1]
    )

    for i in sorted_movies[1:6]:

        print(movies.iloc[i[0]].title)

In [84]:
recommend("Lifeforce")

The Thing
Home
Aliens vs Predator: Requiem
Titan A.E.
Star Trek: Insurrection

In [85]:
from nltk.stem.porter import PorterStemmer # Stemming converts different forms of a word into a common base word.

In [86]:
ps = PorterStemmer()

In [87]:
ps.stem("loving")

'love'

In [88]:
def stem(text):

    L = []

    for i in text.split():

        L.append(ps.stem(i))

    return " ".join(L)

In [89]:
movies["tags"] = movies["tags"].apply(stem)

In [90]:
cv = CountVectorizer(
    max_features=5000,
    stop_words="english"
)

In [91]:
vectors = cv.fit_transform(movies["tags"]).toarray()

In [92]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

In [93]:
recommend("Avatar")

Lifeforce
Aliens vs Predator: Requiem
Battle: Los Angeles
Titan A.E.
Independence Day

In [94]:
recommend("Batman Begins")

The Dark Knight
The Dark Knight Rises
Amidst the Devil's Wings
Batman
Batman & Robin

In [95]:
recommend("Avatar")
recommend("The Dark Knight")
recommend("Interstellar")
recommend("Titanic")
recommend("Iron Man")

Lifeforce
Aliens vs Predator: Requiem
Battle: Los Angeles
Titan A.E.
Independence Day
Batman Begins
The Dark Knight Rises
Batman Returns
Amidst the Devil's Wings
Batman Forever
Space Pirate Captain Harlock
The Martian
Silent Running
Gravity
Apollo 13
Captain Phillips
In the Heart of the Sea
Ghost Ship
The Notebook
The Bounty
Iron Man 2
Iron Man 3
Avengers: Age of Ultron
The Avengers
Thor

In [96]:
print(type(movies))
print(type(similarity))

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>

In [97]:
import pickle

pickle.dump(movies,
            open("../models/movies.pkl","wb"))

pickle.dump(similarity,
            open("../models/similarity.pkl","wb"))